name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
     - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
          token: ${{ secrets.A_SECRET_TOKEN}}
          build: npm run build
          start: npm start